// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Environment struct {
	// Primary key and unique ID for an environment in the system.
	ID pgtype.UUID
	// Preferred name to display when referencing this user, free text could be a real name, partial name, nickname etc.
	Name string
}

type EnvironmentComponent struct {
	// Primary key and unique ID for a component in the system.
	ID pgtype.UUID
	// The environment this component belongs to.
	EnvironmentID pgtype.UUID
	// Name of the component, unique within an environment.
	Name string
	// Name of the Helm chart.
	ChartName string
	// Version of the Helm chart.
	ChartVersion string
	// Registry where the Helm chart is hosted.
	ChartRegistry string
}

type EnvironmentComponentDeployment struct {
	// Primary key and unique ID for a deployment in the system.
	ID pgtype.UUID
	// The environment that this deploy was part of.
	EnvironmentID pgtype.UUID
	// The environment component that was deployed.
	EnvironmentComponentID pgtype.UUID
	// When the deployment was created.
	CreatedAt pgtype.Timestamptz
	// The status of the deployment.
	Status string
}
