// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironmentComponents = `-- name: CountEnvironmentComponents :one
SELECT COUNT(*) FROM environment_components
WHERE environment_id = $1
`

func (q *Queries) CountEnvironmentComponents(ctx context.Context, environmentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentComponents, environmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvironments = `-- name: CountEnvironments :one
SELECT COUNT(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEnvironmentByID = `-- name: DeleteEnvironmentByID :exec
DELETE FROM environments WHERE id = $1
`

func (q *Queries) DeleteEnvironmentByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentByID, id)
	return err
}

const deleteEnvironmentComponentByID = `-- name: DeleteEnvironmentComponentByID :exec
DELETE FROM environment_components WHERE id = $1
`

func (q *Queries) DeleteEnvironmentComponentByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironmentComponentByID, id)
	return err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, environment_id, environment_component_id, created_at, status FROM environment_component_deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (EnvironmentComponentDeployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i EnvironmentComponentDeployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.EnvironmentComponentID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT
    id, name
FROM environments
WHERE
    name = $1
`

func (q *Queries) GetEnvironmentByName(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, name)
	var i Environment
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getEnvironmentComponentByEnvironmentAndName = `-- name: GetEnvironmentComponentByEnvironmentAndName :one
SELECT id, environment_id, name, chart_name, chart_version, chart_registry FROM environment_components
WHERE environment_id = $1 AND name = $2
`

type GetEnvironmentComponentByEnvironmentAndNameParams struct {
	EnvironmentID pgtype.UUID
	Name          string
}

func (q *Queries) GetEnvironmentComponentByEnvironmentAndName(ctx context.Context, arg GetEnvironmentComponentByEnvironmentAndNameParams) (EnvironmentComponent, error) {
	row := q.db.QueryRow(ctx, getEnvironmentComponentByEnvironmentAndName, arg.EnvironmentID, arg.Name)
	var i EnvironmentComponent
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.ChartName,
		&i.ChartVersion,
		&i.ChartRegistry,
	)
	return i, err
}

const listEnvironmentComponents = `-- name: ListEnvironmentComponents :many
SELECT id, environment_id, name, chart_name, chart_version, chart_registry FROM environment_components
WHERE environment_id = $1
ORDER BY name ASC
LIMIT $2
OFFSET $3
`

type ListEnvironmentComponentsParams struct {
	EnvironmentID pgtype.UUID
	Limit         int32
	Offset        int32
}

func (q *Queries) ListEnvironmentComponents(ctx context.Context, arg ListEnvironmentComponentsParams) ([]EnvironmentComponent, error) {
	rows, err := q.db.Query(ctx, listEnvironmentComponents, arg.EnvironmentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentComponent
	for rows.Next() {
		var i EnvironmentComponent
		if err := rows.Scan(
			&i.ID,
			&i.EnvironmentID,
			&i.Name,
			&i.ChartName,
			&i.ChartVersion,
			&i.ChartRegistry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name
FROM environments
ORDER BY name ASC
LIMIT $1
OFFSET $2
`

type ListEnvironmentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeployment = `-- name: UpsertDeployment :one
INSERT INTO environment_component_deployments (id, environment_id, environment_component_id, created_at, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status
RETURNING id, environment_id, environment_component_id, created_at, status
`

type UpsertDeploymentParams struct {
	ID                     pgtype.UUID
	EnvironmentID          pgtype.UUID
	EnvironmentComponentID pgtype.UUID
	CreatedAt              pgtype.Timestamptz
	Status                 string
}

func (q *Queries) UpsertDeployment(ctx context.Context, arg UpsertDeploymentParams) (EnvironmentComponentDeployment, error) {
	row := q.db.QueryRow(ctx, upsertDeployment,
		arg.ID,
		arg.EnvironmentID,
		arg.EnvironmentComponentID,
		arg.CreatedAt,
		arg.Status,
	)
	var i EnvironmentComponentDeployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.EnvironmentComponentID,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO environments (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

type UpsertEnvironmentParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, upsertEnvironment, arg.ID, arg.Name)
	var i Environment
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertEnvironmentComponent = `-- name: UpsertEnvironmentComponent :one
INSERT INTO environment_components (id, environment_id, name, chart_name, chart_version, chart_registry)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    chart_name = EXCLUDED.chart_name,
    chart_version = EXCLUDED.chart_version,
    chart_registry = EXCLUDED.chart_registry
RETURNING id, environment_id, name, chart_name, chart_version, chart_registry
`

type UpsertEnvironmentComponentParams struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	Name          string
	ChartName     string
	ChartVersion  string
	ChartRegistry string
}

func (q *Queries) UpsertEnvironmentComponent(ctx context.Context, arg UpsertEnvironmentComponentParams) (EnvironmentComponent, error) {
	row := q.db.QueryRow(ctx, upsertEnvironmentComponent,
		arg.ID,
		arg.EnvironmentID,
		arg.Name,
		arg.ChartName,
		arg.ChartVersion,
		arg.ChartRegistry,
	)
	var i EnvironmentComponent
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.Name,
		&i.ChartName,
		&i.ChartVersion,
		&i.ChartRegistry,
	)
	return i, err
}
